// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpawnEnemyData.proto

#ifndef PROTOBUF_SpawnEnemyData_2eproto__INCLUDED
#define PROTOBUF_SpawnEnemyData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_SpawnEnemyData_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSpawnEnemyDataImpl();
void InitDefaultsSpawnEnemyData();
inline void InitDefaults() {
  InitDefaultsSpawnEnemyData();
}
}  // namespace protobuf_SpawnEnemyData_2eproto
namespace mongo {
class SpawnEnemyData;
class SpawnEnemyDataDefaultTypeInternal;
extern SpawnEnemyDataDefaultTypeInternal _SpawnEnemyData_default_instance_;
}  // namespace mongo
namespace mongo {

// ===================================================================

class SpawnEnemyData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mongo.SpawnEnemyData) */ {
 public:
  SpawnEnemyData();
  virtual ~SpawnEnemyData();

  SpawnEnemyData(const SpawnEnemyData& from);

  inline SpawnEnemyData& operator=(const SpawnEnemyData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SpawnEnemyData(SpawnEnemyData&& from) noexcept
    : SpawnEnemyData() {
    *this = ::std::move(from);
  }

  inline SpawnEnemyData& operator=(SpawnEnemyData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SpawnEnemyData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SpawnEnemyData* internal_default_instance() {
    return reinterpret_cast<const SpawnEnemyData*>(
               &_SpawnEnemyData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SpawnEnemyData* other);
  friend void swap(SpawnEnemyData& a, SpawnEnemyData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SpawnEnemyData* New() const PROTOBUF_FINAL { return New(NULL); }

  SpawnEnemyData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SpawnEnemyData& from);
  void MergeFrom(const SpawnEnemyData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SpawnEnemyData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 1;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string uuid = 2;
  void clear_uuid();
  static const int kUuidFieldNumber = 2;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  #if LANG_CXX11
  void set_uuid(::std::string&& value);
  #endif
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // int64 timestamp = 3;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // uint32 x = 4;
  void clear_x();
  static const int kXFieldNumber = 4;
  ::google::protobuf::uint32 x() const;
  void set_x(::google::protobuf::uint32 value);

  // uint32 y = 5;
  void clear_y();
  static const int kYFieldNumber = 5;
  ::google::protobuf::uint32 y() const;
  void set_y(::google::protobuf::uint32 value);

  // uint32 z = 6;
  void clear_z();
  static const int kZFieldNumber = 6;
  ::google::protobuf::uint32 z() const;
  void set_z(::google::protobuf::uint32 value);

  // uint32 enemy_id = 7;
  void clear_enemy_id();
  static const int kEnemyIdFieldNumber = 7;
  ::google::protobuf::uint32 enemy_id() const;
  void set_enemy_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mongo.SpawnEnemyData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::uint32 x_;
  ::google::protobuf::uint32 y_;
  ::google::protobuf::uint32 z_;
  ::google::protobuf::uint32 enemy_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_SpawnEnemyData_2eproto::TableStruct;
  friend void ::protobuf_SpawnEnemyData_2eproto::InitDefaultsSpawnEnemyDataImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SpawnEnemyData

// string username = 1;
inline void SpawnEnemyData::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SpawnEnemyData::username() const {
  // @@protoc_insertion_point(field_get:mongo.SpawnEnemyData.username)
  return username_.GetNoArena();
}
inline void SpawnEnemyData::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mongo.SpawnEnemyData.username)
}
#if LANG_CXX11
inline void SpawnEnemyData::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mongo.SpawnEnemyData.username)
}
#endif
inline void SpawnEnemyData::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mongo.SpawnEnemyData.username)
}
inline void SpawnEnemyData::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mongo.SpawnEnemyData.username)
}
inline ::std::string* SpawnEnemyData::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:mongo.SpawnEnemyData.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SpawnEnemyData::release_username() {
  // @@protoc_insertion_point(field_release:mongo.SpawnEnemyData.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpawnEnemyData::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:mongo.SpawnEnemyData.username)
}

// string uuid = 2;
inline void SpawnEnemyData::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SpawnEnemyData::uuid() const {
  // @@protoc_insertion_point(field_get:mongo.SpawnEnemyData.uuid)
  return uuid_.GetNoArena();
}
inline void SpawnEnemyData::set_uuid(const ::std::string& value) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mongo.SpawnEnemyData.uuid)
}
#if LANG_CXX11
inline void SpawnEnemyData::set_uuid(::std::string&& value) {
  
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mongo.SpawnEnemyData.uuid)
}
#endif
inline void SpawnEnemyData::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mongo.SpawnEnemyData.uuid)
}
inline void SpawnEnemyData::set_uuid(const char* value, size_t size) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mongo.SpawnEnemyData.uuid)
}
inline ::std::string* SpawnEnemyData::mutable_uuid() {
  
  // @@protoc_insertion_point(field_mutable:mongo.SpawnEnemyData.uuid)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SpawnEnemyData::release_uuid() {
  // @@protoc_insertion_point(field_release:mongo.SpawnEnemyData.uuid)
  
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpawnEnemyData::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    
  } else {
    
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:mongo.SpawnEnemyData.uuid)
}

// int64 timestamp = 3;
inline void SpawnEnemyData::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 SpawnEnemyData::timestamp() const {
  // @@protoc_insertion_point(field_get:mongo.SpawnEnemyData.timestamp)
  return timestamp_;
}
inline void SpawnEnemyData::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:mongo.SpawnEnemyData.timestamp)
}

// uint32 x = 4;
inline void SpawnEnemyData::clear_x() {
  x_ = 0u;
}
inline ::google::protobuf::uint32 SpawnEnemyData::x() const {
  // @@protoc_insertion_point(field_get:mongo.SpawnEnemyData.x)
  return x_;
}
inline void SpawnEnemyData::set_x(::google::protobuf::uint32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:mongo.SpawnEnemyData.x)
}

// uint32 y = 5;
inline void SpawnEnemyData::clear_y() {
  y_ = 0u;
}
inline ::google::protobuf::uint32 SpawnEnemyData::y() const {
  // @@protoc_insertion_point(field_get:mongo.SpawnEnemyData.y)
  return y_;
}
inline void SpawnEnemyData::set_y(::google::protobuf::uint32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:mongo.SpawnEnemyData.y)
}

// uint32 z = 6;
inline void SpawnEnemyData::clear_z() {
  z_ = 0u;
}
inline ::google::protobuf::uint32 SpawnEnemyData::z() const {
  // @@protoc_insertion_point(field_get:mongo.SpawnEnemyData.z)
  return z_;
}
inline void SpawnEnemyData::set_z(::google::protobuf::uint32 value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:mongo.SpawnEnemyData.z)
}

// uint32 enemy_id = 7;
inline void SpawnEnemyData::clear_enemy_id() {
  enemy_id_ = 0u;
}
inline ::google::protobuf::uint32 SpawnEnemyData::enemy_id() const {
  // @@protoc_insertion_point(field_get:mongo.SpawnEnemyData.enemy_id)
  return enemy_id_;
}
inline void SpawnEnemyData::set_enemy_id(::google::protobuf::uint32 value) {
  
  enemy_id_ = value;
  // @@protoc_insertion_point(field_set:mongo.SpawnEnemyData.enemy_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace mongo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SpawnEnemyData_2eproto__INCLUDED
